# permissions for end users to view dbaaspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaaspolicy-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaaspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaaspolicies/status
  verbs:
  - get
