# permissions for end users to edit dbaaspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaaspolicy-editor-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaaspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaaspolicies/status
  verbs:
  - get
