
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - atlas.mongodb.com
  resources:
  - atlasservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - atlas.mongodb.com
  resources:
  - atlasservices/status
  verbs:
  - get
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasservices/finalizers
  verbs:
  - update
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasservices/status
  verbs:
  - get
  - patch
  - update
