apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbaasconnections.dbaas.redhat.com
  annotations:
    service.binding/credentials: 'path={.status.credentialsRef.name},objectType=Secret'
    service.binding/configuration: 'path={.status.connectionInfoRef.name},objectType=ConfigMap'
