apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbaasconnections.dbaas.redhat.com
  annotations:
    service.binding/type: 'path={.spec.type}'
    service.binding/provider: 'path={.spec.provider}'
    service.binding/db.name: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.host: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.port: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.user: 'path={.status.dbCredentials},objectType=Secret'
    service.binding/db.password: 'path={.status.dbCredentials},objectType=Secret'