apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSTenant
metadata:
  name: sample
spec:
  inventoryNamespace: foo
  authz:
    serviceAdmin:
      users:
        - admin1
        - admin2
    developer:
      groups:
        - system:authenticated
