apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: accounts.atlas.mongodb.com
spec:
  conversion:
    strategy: None
  group: atlas.mongodb.com
  names:
    kind: AtlasAccount
    listKind: AtlasAccountList
    plural: accounts
    singular: account
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: AtlasAccount is a sample Schema for supporting DBaaS inventories
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: DBaaSInventorySpec defines the desired state of AtlasAccount
              properties:
                credentialsRef:
                  description: The secret storing the vendor-specific connection credentials to use with the API endpoint. The secret may be placed in a separate namespace to control access.
                  properties:
                    name:
                      description: The name for object of known type
                      type: string
                    namespace:
                      description: The namespace where object of known type is store
                      type: string
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
