name: Check PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
#             https://github.com/marketplace/actions/enforce-pr-labels
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          BANNED_LABELS: "hold"
#          REQUIRED_LABELS_ANY: "bug,enhancement,skip-changelog"
#          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['bug','enhancement','skip-changelog']"
